events {}

http {
    server {
        listen 80;
        server_name fastapi-roniprojects.click ; # Seu domínio aqui

        # Necessário para o desafio de validação do Certbot
        location /.well-known/acme-challenge/ {
            root /var/www/html;
        }

        # Redireciona temporariamente tudo o mais para HTTP (enquanto pegamos o certificado)
        location / {
            return 301 http://$host$request_uri;
        }
    }
}