name: Deploy Nova Aplicacao FastAPI

on:
  push:
    branches:
      - main # O deploy ocorre sempre que houver um  push na main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Deploy via SSH na AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }} # Usuário 'ubuntu'
          key: ${{ secrets.EC2_SSH_KEY }} # Chave .pem privada
          script: |
            # Entra na pasta do projeto
            cd NovaBank-AI-Core/
            
            # Puxa o código novo
            git pull origin main
            
            # Reconstrói a imagem da API e reinicia o container
            docker-compose up -d --build web
            
            # Remove imagens antigas soltas para não lotar o disco da EC2
            docker image prune -f